### ISSUE TITLE
Unity导入生成UGUI，Not Found Sprite At:XXX，图片已在路径上找不到

### ISSUE THREAD

**Issue by CodeEngieer** [ZeroUltra/PSD2Unity#1]
Unity导入控制台报错Sprite Not Found，明明图片已经导入却找不到。
 
 ![enter description here](https://raw.githubusercontent.com/CodeEngieer/Demo/main/小书匠/1688547340922.png)
![enter description here](https://raw.githubusercontent.com/CodeEngieer/Demo/main/小书匠/1688547380615.png)

**Comment by ZeroUltra** [comment]
检查一下你的图片类型是否为sprite类型

**Comment by CodeEngieer** [comment]
图片类型就是Sprite，显示Not Found Sprite，打印出来的地址就是Sprite的地址

**Comment by ZeroUltra** [comment]
很明显你的图片类型是texture啊,你在图片导入设置
![image](https://github.com/ZeroUltra/PSD2Unity/assets/38253805/c6ef5cb6-3fa0-489b-bb67-247e29378984)

**Comment by CodeEngieer** [comment]
要我把整个工程文件给你吗？用不了了
![enter description here](https://raw.githubusercontent.com/CodeEngieer/Demo/main/小书匠/1688550463981.png)

**Comment by ZeroUltra** [comment]
![image](https://github.com/ZeroUltra/PSD2Unity/assets/38253805/66c75f09-67ca-497b-af72-6863cbafe079)
改成
![image](https://github.com/ZeroUltra/PSD2Unity/assets/38253805/835ef315-a03e-483c-9fed-b2c2edb7d41a)
不然这不是一个sprite图片

**Comment by CodeEngieer** [comment]
还有一个问题PS导出的时候，报这个错。但能正常导出。![enter description here](https://raw.githubusercontent.com/CodeEngieer/Demo/main/小书匠/1688551986684.png)

**Comment by ZeroUltra** [comment]
这是存在相同图片名称的问题
代码中会按照图片名字查找对应图片,如果有相同文件名,那么可能会找到同一张图片,最后呈现的就是个错误结果
解决方案就是不要把PS图层名字名称设置一样

**Comment by ZeroUltra** [comment]
还有其他问题吗?

**Comment by CodeEngieer** [comment]
已经全部解决了，谢谢一些基础问题困扰一下午。已经star了
